# Site settings
title: La Brigada de la Basura
email: your-email@domain.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: css
  style: compressed

# Handling Reading
exclude: ["LICENSE", "README.md"]
